// HSK Character Data with Pinyin and Meanings
const HSK_DATA = {
    1: [
        { char: '你', pinyin: 'nǐ', meaning: 'you' },
        { char: '好', pinyin: 'hǎo', meaning: 'good' },
        { char: '我', pinyin: 'wǒ', meaning: 'I, me' },
        { char: '是', pinyin: 'shì', meaning: 'to be' },
        { char: '他', pinyin: 'tā', meaning: 'he' },
        { char: '她', pinyin: 'tā', meaning: 'she' },
        { char: '们', pinyin: 'men', meaning: 'plural marker' },
        { char: '这', pinyin: 'zhè', meaning: 'this' },
        { char: '那', pinyin: 'nà', meaning: 'that' },
        { char: '哪', pinyin: 'nǎ', meaning: 'which' },
        { char: '谁', pinyin: 'shéi', meaning: 'who' },
        { char: '什', pinyin: 'shén', meaning: 'what' },
        { char: '么', pinyin: 'me', meaning: '(question particle)' },
        { char: '多', pinyin: 'duō', meaning: 'many, much' },
        { char: '少', pinyin: 'shǎo', meaning: 'few, little' },
        { char: '几', pinyin: 'jǐ', meaning: 'how many' },
        { char: '一', pinyin: 'yī', meaning: 'one' },
        { char: '二', pinyin: 'èr', meaning: 'two' },
        { char: '三', pinyin: 'sān', meaning: 'three' },
        { char: '四', pinyin: 'sì', meaning: 'four' },
        { char: '五', pinyin: 'wǔ', meaning: 'five' },
        { char: '六', pinyin: 'liù', meaning: 'six' },
        { char: '七', pinyin: 'qī', meaning: 'seven' },
        { char: '八', pinyin: 'bā', meaning: 'eight' },
        { char: '九', pinyin: 'jiǔ', meaning: 'nine' },
        { char: '十', pinyin: 'shí', meaning: 'ten' },
        { char: '百', pinyin: 'bǎi', meaning: 'hundred' },
        { char: '千', pinyin: 'qiān', meaning: 'thousand' },
        { char: '万', pinyin: 'wàn', meaning: 'ten thousand' },
        { char: '个', pinyin: 'gè', meaning: '(measure word)' },
        { char: '人', pinyin: 'rén', meaning: 'person' },
        { char: '大', pinyin: 'dà', meaning: 'big' },
        { char: '小', pinyin: 'xiǎo', meaning: 'small' },
        { char: '中', pinyin: 'zhōng', meaning: 'middle, China' },
        { char: '国', pinyin: 'guó', meaning: 'country' },
        { char: '年', pinyin: 'nián', meaning: 'year' },
        { char: '月', pinyin: 'yuè', meaning: 'month, moon' },
        { char: '日', pinyin: 'rì', meaning: 'day, sun' },
        { char: '今', pinyin: 'jīn', meaning: 'today, now' },
        { char: '天', pinyin: 'tiān', meaning: 'day, sky' },
        { char: '明', pinyin: 'míng', meaning: 'bright, tomorrow' },
        { char: '昨', pinyin: 'zuó', meaning: 'yesterday' },
        { char: '上', pinyin: 'shàng', meaning: 'up, on' },
        { char: '下', pinyin: 'xià', meaning: 'down, under' },
        { char: '前', pinyin: 'qián', meaning: 'front, before' },
        { char: '后', pinyin: 'hòu', meaning: 'back, after' },
        { char: '里', pinyin: 'lǐ', meaning: 'inside' },
        { char: '外', pinyin: 'wài', meaning: 'outside' },
        { char: '左', pinyin: 'zuǒ', meaning: 'left' },
        { char: '右', pinyin: 'yòu', meaning: 'right' },
        { char: '东', pinyin: 'dōng', meaning: 'east' },
        { char: '西', pinyin: 'xī', meaning: 'west' },
        { char: '南', pinyin: 'nán', meaning: 'south' },
        { char: '北', pinyin: 'běi', meaning: 'north' },
        { char: '家', pinyin: 'jiā', meaning: 'home, family' },
        { char: '学', pinyin: 'xué', meaning: 'to study' },
        { char: '校', pinyin: 'xiào', meaning: 'school' },
        { char: '生', pinyin: 'shēng', meaning: 'student, life' },
        { char: '老', pinyin: 'lǎo', meaning: 'old' },
        { char: '师', pinyin: 'shī', meaning: 'teacher' },
        { char: '书', pinyin: 'shū', meaning: 'book' },
        { char: '本', pinyin: 'běn', meaning: 'root, (measure word)' },
        { char: '字', pinyin: 'zì', meaning: 'character, word' },
        { char: '写', pinyin: 'xiě', meaning: 'to write' },
        { char: '读', pinyin: 'dú', meaning: 'to read' },
        { char: '说', pinyin: 'shuō', meaning: 'to speak' },
        { char: '话', pinyin: 'huà', meaning: 'speech, words' },
        { char: '听', pinyin: 'tīng', meaning: 'to listen' },
        { char: '看', pinyin: 'kàn', meaning: 'to look, to see' },
        { char: '见', pinyin: 'jiàn', meaning: 'to see, to meet' },
        { char: '叫', pinyin: 'jiào', meaning: 'to call' },
        { char: '名', pinyin: 'míng', meaning: 'name' },
        { char: '吃', pinyin: 'chī', meaning: 'to eat' },
        { char: '喝', pinyin: 'hē', meaning: 'to drink' },
        { char: '水', pinyin: 'shuǐ', meaning: 'water' },
        { char: '茶', pinyin: 'chá', meaning: 'tea' },
        { char: '饭', pinyin: 'fàn', meaning: 'rice, meal' },
        { char: '菜', pinyin: 'cài', meaning: 'vegetable, dish' },
        { char: '肉', pinyin: 'ròu', meaning: 'meat' },
        { char: '鱼', pinyin: 'yú', meaning: 'fish' },
        { char: '果', pinyin: 'guǒ', meaning: 'fruit' },
        { char: '苹', pinyin: 'píng', meaning: 'apple' },
        { char: '买', pinyin: 'mǎi', meaning: 'to buy' },
        { char: '卖', pinyin: 'mài', meaning: 'to sell' },
        { char: '钱', pinyin: 'qián', meaning: 'money' },
        { char: '块', pinyin: 'kuài', meaning: 'piece, yuan' },
        { char: '元', pinyin: 'yuán', meaning: 'yuan (currency)' },
        { char: '有', pinyin: 'yǒu', meaning: 'to have' },
        { char: '没', pinyin: 'méi', meaning: 'not have' },
        { char: '不', pinyin: 'bù', meaning: 'not' },
        { char: '很', pinyin: 'hěn', meaning: 'very' },
        { char: '太', pinyin: 'tài', meaning: 'too' },
        { char: '都', pinyin: 'dōu', meaning: 'all, both' },
        { char: '也', pinyin: 'yě', meaning: 'also' },
        { char: '和', pinyin: 'hé', meaning: 'and' },
        { char: '在', pinyin: 'zài', meaning: 'at, in' },
        { char: '去', pinyin: 'qù', meaning: 'to go' },
        { char: '来', pinyin: 'lái', meaning: 'to come' },
        { char: '回', pinyin: 'huí', meaning: 'to return' },
        { char: '到', pinyin: 'dào', meaning: 'to arrive' },
        { char: '走', pinyin: 'zǒu', meaning: 'to walk' },
        { char: '坐', pinyin: 'zuò', meaning: 'to sit' },
        { char: '站', pinyin: 'zhàn', meaning: 'to stand' },
        { char: '住', pinyin: 'zhù', meaning: 'to live' },
        { char: '做', pinyin: 'zuò', meaning: 'to do' },
        { char: '工', pinyin: 'gōng', meaning: 'work' },
        { char: '作', pinyin: 'zuò', meaning: 'work, to do' },
        { char: '想', pinyin: 'xiǎng', meaning: 'to think, to want' },
        { char: '要', pinyin: 'yào', meaning: 'to want' },
        { char: '会', pinyin: 'huì', meaning: 'can, will' },
        { char: '能', pinyin: 'néng', meaning: 'can, able' },
        { char: '可', pinyin: 'kě', meaning: 'can, may' },
        { char: '以', pinyin: 'yǐ', meaning: 'with, by' },
        { char: '爱', pinyin: 'ài', meaning: 'to love' },
        { char: '喜', pinyin: 'xǐ', meaning: 'happy, to like' },
        { char: '欢', pinyin: 'huān', meaning: 'happy, joyful' },
        { char: '高', pinyin: 'gāo', meaning: 'tall, high' },
        { char: '兴', pinyin: 'xìng', meaning: 'mood, interest' },
        { char: '热', pinyin: 'rè', meaning: 'hot' },
        { char: '冷', pinyin: 'lěng', meaning: 'cold' },
        { char: '快', pinyin: 'kuài', meaning: 'fast, happy' },
        { char: '慢', pinyin: 'màn', meaning: 'slow' },
        { char: '长', pinyin: 'cháng', meaning: 'long' },
        { char: '短', pinyin: 'duǎn', meaning: 'short' },
        { char: '新', pinyin: 'xīn', meaning: 'new' },
        { char: '旧', pinyin: 'jiù', meaning: 'old (things)' },
        { char: '对', pinyin: 'duì', meaning: 'correct, to' },
        { char: '错', pinyin: 'cuò', meaning: 'wrong' },
        { char: '开', pinyin: 'kāi', meaning: 'to open' },
        { char: '关', pinyin: 'guān', meaning: 'to close' },
        { char: '车', pinyin: 'chē', meaning: 'car, vehicle' },
        { char: '飞', pinyin: 'fēi', meaning: 'to fly' },
        { char: '机', pinyin: 'jī', meaning: 'machine' },
        { char: '电', pinyin: 'diàn', meaning: 'electricity' },
        { char: '视', pinyin: 'shì', meaning: 'to look, vision' },
        { char: '脑', pinyin: 'nǎo', meaning: 'brain' },
        { char: '手', pinyin: 'shǒu', meaning: 'hand' },
        { char: '头', pinyin: 'tóu', meaning: 'head' },
        { char: '眼', pinyin: 'yǎn', meaning: 'eye' },
        { char: '睛', pinyin: 'jīng', meaning: 'eyeball' },
        { char: '耳', pinyin: 'ěr', meaning: 'ear' },
        { char: '口', pinyin: 'kǒu', meaning: 'mouth' },
        { char: '心', pinyin: 'xīn', meaning: 'heart' },
        { char: '身', pinyin: 'shēn', meaning: 'body' },
        { char: '体', pinyin: 'tǐ', meaning: 'body' },
        { char: '爸', pinyin: 'bà', meaning: 'father' },
        { char: '妈', pinyin: 'mā', meaning: 'mother' },
        { char: '儿', pinyin: 'ér', meaning: 'son, child' },
        { char: '子', pinyin: 'zǐ', meaning: 'child, son' },
        { char: '女', pinyin: 'nǚ', meaning: 'female, daughter' },
        { char: '朋', pinyin: 'péng', meaning: 'friend' },
        { char: '友', pinyin: 'yǒu', meaning: 'friend' }
    ],
    2: [
        { char: '因', pinyin: 'yīn', meaning: 'because' },
        { char: '为', pinyin: 'wèi', meaning: 'for, because' },
        { char: '所', pinyin: 'suǒ', meaning: 'place, so' },
        { char: '但', pinyin: 'dàn', meaning: 'but' },
        { char: '虽', pinyin: 'suī', meaning: 'although' },
        { char: '然', pinyin: 'rán', meaning: 'correct, so' },
        { char: '如', pinyin: 'rú', meaning: 'like, if' },
        { char: '比', pinyin: 'bǐ', meaning: 'compare' },
        { char: '更', pinyin: 'gèng', meaning: 'more, even more' },
        { char: '最', pinyin: 'zuì', meaning: 'most' },
        { char: '第', pinyin: 'dì', meaning: 'ordinal prefix' },
        { char: '次', pinyin: 'cì', meaning: 'time, order' },
        { char: '每', pinyin: 'měi', meaning: 'every' },
        { char: '些', pinyin: 'xiē', meaning: 'some' },
        { char: '两', pinyin: 'liǎng', meaning: 'two (quantity)' },
        { char: '半', pinyin: 'bàn', meaning: 'half' },
        { char: '分', pinyin: 'fēn', meaning: 'minute, divide' },
        { char: '刻', pinyin: 'kè', meaning: 'quarter hour' },
        { char: '点', pinyin: 'diǎn', meaning: 'point, o\'clock' },
        { char: '早', pinyin: 'zǎo', meaning: 'early, morning' },
        { char: '晚', pinyin: 'wǎn', meaning: 'late, evening' },
        { char: '午', pinyin: 'wǔ', meaning: 'noon' },
        { char: '时', pinyin: 'shí', meaning: 'time, hour' },
        { char: '候', pinyin: 'hòu', meaning: 'time, wait' },
        { char: '间', pinyin: 'jiān', meaning: 'between, room' },
        { char: '周', pinyin: 'zhōu', meaning: 'week' },
        { char: '星', pinyin: 'xīng', meaning: 'star' },
        { char: '期', pinyin: 'qī', meaning: 'period' },
        { char: '号', pinyin: 'hào', meaning: 'number, date' },
        { char: '岁', pinyin: 'suì', meaning: 'years old' },
        { char: '从', pinyin: 'cóng', meaning: 'from' },
        { char: '往', pinyin: 'wǎng', meaning: 'toward' },
        { char: '向', pinyin: 'xiàng', meaning: 'toward' },
        { char: '过', pinyin: 'guò', meaning: 'to pass' },
        { char: '着', pinyin: 'zhe', meaning: 'aspect particle' },
        { char: '了', pinyin: 'le', meaning: 'aspect particle' },
        { char: '把', pinyin: 'bǎ', meaning: 'take, handle' },
        { char: '被', pinyin: 'bèi', meaning: 'by (passive)' },
        { char: '让', pinyin: 'ràng', meaning: 'to let' },
        { char: '给', pinyin: 'gěi', meaning: 'to give' },
        { char: '跟', pinyin: 'gēn', meaning: 'with, follow' },
        { char: '比', pinyin: 'bǐ', meaning: 'compare, than' },
        { char: '像', pinyin: 'xiàng', meaning: 'like, resemble' },
        { char: '还', pinyin: 'hái', meaning: 'still, also' },
        { char: '再', pinyin: 'zài', meaning: 'again' },
        { char: '又', pinyin: 'yòu', meaning: 'again, also' },
        { char: '才', pinyin: 'cái', meaning: 'just, only' },
        { char: '就', pinyin: 'jiù', meaning: 'then, just' },
        { char: '已', pinyin: 'yǐ', meaning: 'already' },
        { char: '经', pinyin: 'jīng', meaning: 'pass through' },
        { char: '正', pinyin: 'zhèng', meaning: 'just, right' },
        { char: '先', pinyin: 'xiān', meaning: 'first' },
        { char: '后', pinyin: 'hòu', meaning: 'after' },
        { char: '边', pinyin: 'biān', meaning: 'side' },
        { char: '旁', pinyin: 'páng', meaning: 'beside' },
        { char: '近', pinyin: 'jìn', meaning: 'near' },
        { char: '远', pinyin: 'yuǎn', meaning: 'far' },
        { char: '进', pinyin: 'jìn', meaning: 'to enter' },
        { char: '出', pinyin: 'chū', meaning: 'to exit' },
        { char: '起', pinyin: 'qǐ', meaning: 'to rise' },
        { char: '床', pinyin: 'chuáng', meaning: 'bed' },
        { char: '睡', pinyin: 'shuì', meaning: 'to sleep' },
        { char: '觉', pinyin: 'jiào', meaning: 'sleep, feel' },
        { char: '休', pinyin: 'xiū', meaning: 'rest' },
        { char: '息', pinyin: 'xī', meaning: 'breath, rest' },
        { char: '忙', pinyin: 'máng', meaning: 'busy' },
        { char: '累', pinyin: 'lèi', meaning: 'tired' },
        { char: '病', pinyin: 'bìng', meaning: 'sick' },
        { char: '药', pinyin: 'yào', meaning: 'medicine' },
        { char: '院', pinyin: 'yuàn', meaning: 'courtyard, hospital' },
        { char: '医', pinyin: 'yī', meaning: 'doctor, medical' },
        { char: '帮', pinyin: 'bāng', meaning: 'to help' },
        { char: '助', pinyin: 'zhù', meaning: 'to help' },
        { char: '问', pinyin: 'wèn', meaning: 'to ask' },
        { char: '题', pinyin: 'tí', meaning: 'topic, problem' },
        { char: '答', pinyin: 'dá', meaning: 'to answer' },
        { char: '试', pinyin: 'shì', meaning: 'to try, test' },
        { char: '考', pinyin: 'kǎo', meaning: 'test, exam' },
        { char: '完', pinyin: 'wán', meaning: 'to finish' },
        { char: '成', pinyin: 'chéng', meaning: 'to become' },
        { char: '功', pinyin: 'gōng', meaning: 'achievement' },
        { char: '准', pinyin: 'zhǔn', meaning: 'accurate, allow' },
        { char: '备', pinyin: 'bèi', meaning: 'prepare' },
        { char: '始', pinyin: 'shǐ', meaning: 'begin' },
        { char: '结', pinyin: 'jié', meaning: 'tie, result' },
        { char: '束', pinyin: 'shù', meaning: 'bundle, end' },
        { char: '玩', pinyin: 'wán', meaning: 'to play' },
        { char: '笑', pinyin: 'xiào', meaning: 'to laugh' },
        { char: '哭', pinyin: 'kū', meaning: 'to cry' },
        { char: '怕', pinyin: 'pà', meaning: 'to fear' },
        { char: '急', pinyin: 'jí', meaning: 'urgent, anxious' },
        { char: '担', pinyin: 'dān', meaning: 'to carry, worry' },
        { char: '希', pinyin: 'xī', meaning: 'hope' },
        { char: '望', pinyin: 'wàng', meaning: 'hope, look' },
        { char: '相', pinyin: 'xiāng', meaning: 'mutual' },
        { char: '信', pinyin: 'xìn', meaning: 'believe, letter' },
        { char: '送', pinyin: 'sòng', meaning: 'to send' },
        { char: '接', pinyin: 'jiē', meaning: 'to receive' },
        { char: '拿', pinyin: 'ná', meaning: 'to take' },
        { char: '放', pinyin: 'fàng', meaning: 'to put' },
        { char: '找', pinyin: 'zhǎo', meaning: 'to look for' },
        { char: '等', pinyin: 'děng', meaning: 'to wait' },
        { char: '穿', pinyin: 'chuān', meaning: 'to wear' },
        { char: '衣', pinyin: 'yī', meaning: 'clothes' },
        { char: '服', pinyin: 'fú', meaning: 'clothes' },
        { char: '鞋', pinyin: 'xié', meaning: 'shoes' },
        { char: '帽', pinyin: 'mào', meaning: 'hat' },
        { char: '裤', pinyin: 'kù', meaning: 'pants' },
        { char: '红', pinyin: 'hóng', meaning: 'red' },
        { char: '黄', pinyin: 'huáng', meaning: 'yellow' },
        { char: '蓝', pinyin: 'lán', meaning: 'blue' },
        { char: '绿', pinyin: 'lǜ', meaning: 'green' },
        { char: '白', pinyin: 'bái', meaning: 'white' },
        { char: '黑', pinyin: 'hēi', meaning: 'black' },
        { char: '颜', pinyin: 'yán', meaning: 'color' },
        { char: '色', pinyin: 'sè', meaning: 'color' },
        { char: '漂', pinyin: 'piào', meaning: 'beautiful' },
        { char: '亮', pinyin: 'liàng', meaning: 'bright' },
        { char: '贵', pinyin: 'guì', meaning: 'expensive' },
        { char: '便', pinyin: 'pián', meaning: 'cheap, convenient' },
        { char: '宜', pinyin: 'yí', meaning: 'suitable' }
    ],
    3: [
        { char: '必', pinyin: 'bì', meaning: 'must' },
        { char: '须', pinyin: 'xū', meaning: 'must, need' },
        { char: '应', pinyin: 'yīng', meaning: 'should' },
        { char: '该', pinyin: 'gāi', meaning: 'should' },
        { char: '需', pinyin: 'xū', meaning: 'need' },
        { char: '愿', pinyin: 'yuàn', meaning: 'willing' },
        { char: '意', pinyin: 'yì', meaning: 'meaning, intention' },
        { char: '决', pinyin: 'jué', meaning: 'decide' },
        { char: '定', pinyin: 'dìng', meaning: 'decide, fixed' },
        { char: '选', pinyin: 'xuǎn', meaning: 'choose' },
        { char: '择', pinyin: 'zé', meaning: 'choose' },
        { char: '计', pinyin: 'jì', meaning: 'plan, count' },
        { char: '划', pinyin: 'huà', meaning: 'plan' },
        { char: '安', pinyin: 'ān', meaning: 'peaceful, safe' },
        { char: '排', pinyin: 'pái', meaning: 'arrange, row' },
        { char: '组', pinyin: 'zǔ', meaning: 'group' },
        { char: '织', pinyin: 'zhī', meaning: 'weave, organize' },
        { char: '管', pinyin: 'guǎn', meaning: 'manage, tube' },
        { char: '理', pinyin: 'lǐ', meaning: 'reason, manage' },
        { char: '解', pinyin: 'jiě', meaning: 'solve, understand' },
        { char: '释', pinyin: 'shì', meaning: 'explain, release' },
        { char: '证', pinyin: 'zhèng', meaning: 'prove, certificate' },
        { char: '明', pinyin: 'míng', meaning: 'bright, clear' },
        { char: '确', pinyin: 'què', meaning: 'true, certain' },
        { char: '认', pinyin: 'rèn', meaning: 'recognize' },
        { char: '识', pinyin: 'shí', meaning: 'know' },
        { char: '知', pinyin: 'zhī', meaning: 'know' },
        { char: '道', pinyin: 'dào', meaning: 'way, road' },
        { char: '懂', pinyin: 'dǒng', meaning: 'understand' },
        { char: '记', pinyin: 'jì', meaning: 'remember' },
        { char: '忆', pinyin: 'yì', meaning: 'memory' },
        { char: '忘', pinyin: 'wàng', meaning: 'forget' },
        { char: '注', pinyin: 'zhù', meaning: 'pour, note' },
        { char: '思', pinyin: 'sī', meaning: 'think' },
        { char: '考', pinyin: 'kǎo', meaning: 'consider, test' },
        { char: '虑', pinyin: 'lǜ', meaning: 'consider' },
        { char: '研', pinyin: 'yán', meaning: 'research' },
        { char: '究', pinyin: 'jiū', meaning: 'investigate' },
        { char: '发', pinyin: 'fā', meaning: 'send, develop' },
        { char: '现', pinyin: 'xiàn', meaning: 'appear, now' },
        { char: '展', pinyin: 'zhǎn', meaning: 'expand, exhibit' },
        { char: '提', pinyin: 'tí', meaning: 'lift, raise' },
        { char: '高', pinyin: 'gāo', meaning: 'tall, high' },
        { char: '增', pinyin: 'zēng', meaning: 'increase' },
        { char: '加', pinyin: 'jiā', meaning: 'add' },
        { char: '减', pinyin: 'jiǎn', meaning: 'reduce' },
        { char: '少', pinyin: 'shǎo', meaning: 'few, less' },
        { char: '变', pinyin: 'biàn', meaning: 'change' },
        { char: '化', pinyin: 'huà', meaning: 'change, transform' },
        { char: '改', pinyin: 'gǎi', meaning: 'change, correct' },
        { char: '换', pinyin: 'huàn', meaning: 'exchange' },
        { char: '代', pinyin: 'dài', meaning: 'generation, replace' },
        { char: '替', pinyin: 'tì', meaning: 'replace' },
        { char: '保', pinyin: 'bǎo', meaning: 'protect' },
        { char: '护', pinyin: 'hù', meaning: 'protect' },
        { char: '持', pinyin: 'chí', meaning: 'hold' },
        { char: '续', pinyin: 'xù', meaning: 'continue' },
        { char: '坚', pinyin: 'jiān', meaning: 'hard, firm' },
        { char: '强', pinyin: 'qiáng', meaning: 'strong' },
        { char: '弱', pinyin: 'ruò', meaning: 'weak' },
        { char: '轻', pinyin: 'qīng', meaning: 'light' },
        { char: '重', pinyin: 'zhòng', meaning: 'heavy, important' },
        { char: '深', pinyin: 'shēn', meaning: 'deep' },
        { char: '浅', pinyin: 'qiǎn', meaning: 'shallow' },
        { char: '厚', pinyin: 'hòu', meaning: 'thick' },
        { char: '薄', pinyin: 'báo', meaning: 'thin' },
        { char: '宽', pinyin: 'kuān', meaning: 'wide' },
        { char: '窄', pinyin: 'zhǎi', meaning: 'narrow' },
        { char: '满', pinyin: 'mǎn', meaning: 'full' },
        { char: '空', pinyin: 'kōng', meaning: 'empty, sky' },
        { char: '富', pinyin: 'fù', meaning: 'rich' },
        { char: '穷', pinyin: 'qióng', meaning: 'poor' },
        { char: '困', pinyin: 'kùn', meaning: 'difficult, sleepy' },
        { char: '难', pinyin: 'nán', meaning: 'difficult' },
        { char: '易', pinyin: 'yì', meaning: 'easy' },
        { char: '简', pinyin: 'jiǎn', meaning: 'simple' },
        { char: '单', pinyin: 'dān', meaning: 'single, simple' },
        { char: '复', pinyin: 'fù', meaning: 'repeat, complex' },
        { char: '杂', pinyin: 'zá', meaning: 'mixed, complex' },
        { char: '普', pinyin: 'pǔ', meaning: 'universal' },
        { char: '通', pinyin: 'tōng', meaning: 'through, common' },
        { char: '特', pinyin: 'tè', meaning: 'special' },
        { char: '别', pinyin: 'bié', meaning: 'other, special' },
        { char: '具', pinyin: 'jù', meaning: 'tool, possess' },
        { char: '真', pinyin: 'zhēn', meaning: 'real, true' },
        { char: '假', pinyin: 'jiǎ', meaning: 'false, fake' },
        { char: '实', pinyin: 'shí', meaning: 'real, solid' },
        { char: '际', pinyin: 'jì', meaning: 'border, occasion' },
        { char: '景', pinyin: 'jǐng', meaning: 'scenery' },
        { char: '况', pinyin: 'kuàng', meaning: 'situation' },
        { char: '环', pinyin: 'huán', meaning: 'ring, surround' },
        { char: '境', pinyin: 'jìng', meaning: 'border, environment' },
        { char: '气', pinyin: 'qì', meaning: 'air, gas' },
        { char: '候', pinyin: 'hòu', meaning: 'climate, time' },
        { char: '温', pinyin: 'wēn', meaning: 'warm' },
        { char: '度', pinyin: 'dù', meaning: 'degree' },
        { char: '阴', pinyin: 'yīn', meaning: 'cloudy, negative' },
        { char: '晴', pinyin: 'qíng', meaning: 'sunny, clear' },
        { char: '雨', pinyin: 'yǔ', meaning: 'rain' },
        { char: '雪', pinyin: 'xuě', meaning: 'snow' },
        { char: '风', pinyin: 'fēng', meaning: 'wind' },
        { char: '云', pinyin: 'yún', meaning: 'cloud' }
    ],
    4: [
        { char: '政', pinyin: 'zhèng', meaning: 'politics' },
        { char: '府', pinyin: 'fǔ', meaning: 'government' },
        { char: '治', pinyin: 'zhì', meaning: 'govern, cure' },
        { char: '法', pinyin: 'fǎ', meaning: 'law, method' },
        { char: '律', pinyin: 'lǜ', meaning: 'law, rule' },
        { char: '规', pinyin: 'guī', meaning: 'rule' },
        { char: '则', pinyin: 'zé', meaning: 'rule, principle' },
        { char: '制', pinyin: 'zhì', meaning: 'system, make' },
        { char: '度', pinyin: 'dù', meaning: 'degree, system' },
        { char: '权', pinyin: 'quán', meaning: 'power, right' },
        { char: '利', pinyin: 'lì', meaning: 'benefit, sharp' },
        { char: '责', pinyin: 'zé', meaning: 'duty, blame' },
        { char: '任', pinyin: 'rèn', meaning: 'duty, appoint' },
        { char: '务', pinyin: 'wù', meaning: 'affair, duty' },
        { char: '义', pinyin: 'yì', meaning: 'justice, meaning' },
        { char: '德', pinyin: 'dé', meaning: 'virtue, morality' },
        { char: '善', pinyin: 'shàn', meaning: 'good, kind' },
        { char: '恶', pinyin: 'è', meaning: 'evil, bad' },
        { char: '诚', pinyin: 'chéng', meaning: 'honest, sincere' },
        { char: '实', pinyin: 'shí', meaning: 'real, honest' },
        { char: '信', pinyin: 'xìn', meaning: 'trust, believe' },
        { char: '用', pinyin: 'yòng', meaning: 'use' },
        { char: '效', pinyin: 'xiào', meaning: 'effect' },
        { char: '率', pinyin: 'lǜ', meaning: 'rate, lead' },
        { char: '量', pinyin: 'liàng', meaning: 'quantity, measure' },
        { char: '质', pinyin: 'zhì', meaning: 'quality' },
        { char: '标', pinyin: 'biāo', meaning: 'mark, sign' },
        { char: '准', pinyin: 'zhǔn', meaning: 'standard, accurate' },
        { char: '求', pinyin: 'qiú', meaning: 'seek, request' },
        { char: '达', pinyin: 'dá', meaning: 'reach, achieve' },
        { char: '到', pinyin: 'dào', meaning: 'arrive, reach' },
        { char: '获', pinyin: 'huò', meaning: 'obtain' },
        { char: '得', pinyin: 'dé', meaning: 'get, obtain' },
        { char: '失', pinyin: 'shī', meaning: 'lose' },
        { char: '败', pinyin: 'bài', meaning: 'defeat, fail' },
        { char: '胜', pinyin: 'shèng', meaning: 'win, victory' },
        { char: '赢', pinyin: 'yíng', meaning: 'win' },
        { char: '输', pinyin: 'shū', meaning: 'lose, transport' },
        { char: '竞', pinyin: 'jìng', meaning: 'compete' },
        { char: '争', pinyin: 'zhēng', meaning: 'fight, contend' },
        { char: '战', pinyin: 'zhàn', meaning: 'war, battle' },
        { char: '斗', pinyin: 'dòu', meaning: 'fight' },
        { char: '攻', pinyin: 'gōng', meaning: 'attack' },
        { char: '防', pinyin: 'fáng', meaning: 'defend' },
        { char: '守', pinyin: 'shǒu', meaning: 'guard' },
        { char: '卫', pinyin: 'wèi', meaning: 'guard, protect' },
        { char: '军', pinyin: 'jūn', meaning: 'army' },
        { char: '兵', pinyin: 'bīng', meaning: 'soldier' },
        { char: '武', pinyin: 'wǔ', meaning: 'military' },
        { char: '器', pinyin: 'qì', meaning: 'tool, weapon' },
        { char: '科', pinyin: 'kē', meaning: 'science, subject' },
        { char: '技', pinyin: 'jì', meaning: 'skill, technology' },
        { char: '术', pinyin: 'shù', meaning: 'art, technique' },
        { char: '艺', pinyin: 'yì', meaning: 'art, skill' },
        { char: '文', pinyin: 'wén', meaning: 'literature, culture' },
        { char: '章', pinyin: 'zhāng', meaning: 'chapter, article' },
        { char: '句', pinyin: 'jù', meaning: 'sentence' },
        { char: '段', pinyin: 'duàn', meaning: 'paragraph, section' },
        { char: '词', pinyin: 'cí', meaning: 'word' },
        { char: '语', pinyin: 'yǔ', meaning: 'language' },
        { char: '言', pinyin: 'yán', meaning: 'speech, word' },
        { char: '论', pinyin: 'lùn', meaning: 'discuss, theory' },
        { char: '述', pinyin: 'shù', meaning: 'state, narrate' },
        { char: '表', pinyin: 'biǎo', meaning: 'express, table' },
        { char: '达', pinyin: 'dá', meaning: 'express, reach' },
        { char: '传', pinyin: 'chuán', meaning: 'pass, transmit' },
        { char: '播', pinyin: 'bō', meaning: 'broadcast, sow' },
        { char: '报', pinyin: 'bào', meaning: 'report, newspaper' },
        { char: '告', pinyin: 'gào', meaning: 'tell, announce' },
        { char: '布', pinyin: 'bù', meaning: 'cloth, spread' },
        { char: '宣', pinyin: 'xuān', meaning: 'declare' },
        { char: '称', pinyin: 'chēng', meaning: 'call, claim' },
        { char: '谈', pinyin: 'tán', meaning: 'talk' },
        { char: '讨', pinyin: 'tǎo', meaning: 'discuss, ask for' },
        { char: '议', pinyin: 'yì', meaning: 'discuss, opinion' },
        { char: '商', pinyin: 'shāng', meaning: 'commerce, discuss' },
        { char: '业', pinyin: 'yè', meaning: 'business, profession' },
        { char: '贸', pinyin: 'mào', meaning: 'trade' },
        { char: '易', pinyin: 'yì', meaning: 'easy, trade' },
        { char: '交', pinyin: 'jiāo', meaning: 'exchange, hand over' },
        { char: '换', pinyin: 'huàn', meaning: 'exchange' },
        { char: '市', pinyin: 'shì', meaning: 'market, city' },
        { char: '场', pinyin: 'chǎng', meaning: 'field, place' },
        { char: '价', pinyin: 'jià', meaning: 'price' },
        { char: '值', pinyin: 'zhí', meaning: 'value, worth' },
        { char: '资', pinyin: 'zī', meaning: 'capital, fund' },
        { char: '本', pinyin: 'běn', meaning: 'root, capital' },
        { char: '产', pinyin: 'chǎn', meaning: 'produce, property' },
        { char: '品', pinyin: 'pǐn', meaning: 'product, article' },
        { char: '物', pinyin: 'wù', meaning: 'thing, object' },
        { char: '料', pinyin: 'liào', meaning: 'material' },
        { char: '原', pinyin: 'yuán', meaning: 'original, source' },
        { char: '因', pinyin: 'yīn', meaning: 'cause, because' },
        { char: '由', pinyin: 'yóu', meaning: 'from, reason' },
        { char: '根', pinyin: 'gēn', meaning: 'root' },
        { char: '据', pinyin: 'jù', meaning: 'according to' },
        { char: '基', pinyin: 'jī', meaning: 'base, foundation' },
        { char: '础', pinyin: 'chǔ', meaning: 'foundation' },
        { char: '底', pinyin: 'dǐ', meaning: 'bottom' },
        { char: '层', pinyin: 'céng', meaning: 'layer, floor' }
    ],
    5: [
        { char: '哲', pinyin: 'zhé', meaning: 'philosophy' },
        { char: '辩', pinyin: 'biàn', meaning: 'debate' },
        { char: '逻', pinyin: 'luó', meaning: 'logic' },
        { char: '辑', pinyin: 'jí', meaning: 'compile, logic' },
        { char: '推', pinyin: 'tuī', meaning: 'push, infer' },
        { char: '断', pinyin: 'duàn', meaning: 'break, judge' },
        { char: '判', pinyin: 'pàn', meaning: 'judge' },
        { char: '评', pinyin: 'píng', meaning: 'comment, evaluate' },
        { char: '估', pinyin: 'gū', meaning: 'estimate' },
        { char: '测', pinyin: 'cè', meaning: 'measure, test' },
        { char: '验', pinyin: 'yàn', meaning: 'test, verify' },
        { char: '察', pinyin: 'chá', meaning: 'observe' },
        { char: '检', pinyin: 'jiǎn', meaning: 'check, inspect' },
        { char: '查', pinyin: 'chá', meaning: 'check, investigate' },
        { char: '调', pinyin: 'diào', meaning: 'adjust, investigate' },
        { char: '研', pinyin: 'yán', meaning: 'research' },
        { char: '探', pinyin: 'tàn', meaning: 'explore' },
        { char: '索', pinyin: 'suǒ', meaning: 'search, rope' },
        { char: '寻', pinyin: 'xún', meaning: 'seek' },
        { char: '追', pinyin: 'zhuī', meaning: 'chase' },
        { char: '踪', pinyin: 'zōng', meaning: 'trace' },
        { char: '迹', pinyin: 'jì', meaning: 'trace, mark' },
        { char: '痕', pinyin: 'hén', meaning: 'mark, scar' },
        { char: '印', pinyin: 'yìn', meaning: 'print, seal' },
        { char: '象', pinyin: 'xiàng', meaning: 'image, elephant' },
        { char: '征', pinyin: 'zhēng', meaning: 'sign, journey' },
        { char: '兆', pinyin: 'zhào', meaning: 'omen, trillion' },
        { char: '预', pinyin: 'yù', meaning: 'in advance' },
        { char: '防', pinyin: 'fáng', meaning: 'prevent, defend' },
        { char: '避', pinyin: 'bì', meaning: 'avoid' },
        { char: '免', pinyin: 'miǎn', meaning: 'exempt, avoid' },
        { char: '除', pinyin: 'chú', meaning: 'remove, except' },
        { char: '消', pinyin: 'xiāo', meaning: 'disappear' },
        { char: '灭', pinyin: 'miè', meaning: 'extinguish' },
        { char: '毁', pinyin: 'huǐ', meaning: 'destroy' },
        { char: '损', pinyin: 'sǔn', meaning: 'damage, lose' },
        { char: '害', pinyin: 'hài', meaning: 'harm' },
        { char: '伤', pinyin: 'shāng', meaning: 'wound, hurt' },
        { char: '痛', pinyin: 'tòng', meaning: 'pain' },
        { char: '苦', pinyin: 'kǔ', meaning: 'bitter, suffer' },
        { char: '悲', pinyin: 'bēi', meaning: 'sad' },
        { char: '惨', pinyin: 'cǎn', meaning: 'miserable' },
        { char: '惧', pinyin: 'jù', meaning: 'fear' },
        { char: '恐', pinyin: 'kǒng', meaning: 'fear, afraid' },
        { char: '慌', pinyin: 'huāng', meaning: 'panic' },
        { char: '乱', pinyin: 'luàn', meaning: 'chaos, disorder' },
        { char: '混', pinyin: 'hùn', meaning: 'mix, muddy' },
        { char: '杂', pinyin: 'zá', meaning: 'mixed, complex' },
        { char: '繁', pinyin: 'fán', meaning: 'numerous' },
        { char: '荣', pinyin: 'róng', meaning: 'glory, flourish' },
        { char: '兴', pinyin: 'xīng', meaning: 'prosper' },
        { char: '旺', pinyin: 'wàng', meaning: 'prosperous' },
        { char: '盛', pinyin: 'shèng', meaning: 'flourishing' },
        { char: '衰', pinyin: 'shuāi', meaning: 'decline' },
        { char: '落', pinyin: 'luò', meaning: 'fall, drop' },
        { char: '降', pinyin: 'jiàng', meaning: 'fall, descend' },
        { char: '升', pinyin: 'shēng', meaning: 'rise, ascend' },
        { char: '涨', pinyin: 'zhǎng', meaning: 'rise, swell' },
        { char: '跌', pinyin: 'diē', meaning: 'fall, drop' },
        { char: '浮', pinyin: 'fú', meaning: 'float' },
        { char: '沉', pinyin: 'chén', meaning: 'sink' },
        { char: '稳', pinyin: 'wěn', meaning: 'stable' },
        { char: '固', pinyin: 'gù', meaning: 'solid, firm' },
        { char: '牢', pinyin: 'láo', meaning: 'firm, prison' },
        { char: '紧', pinyin: 'jǐn', meaning: 'tight' },
        { char: '松', pinyin: 'sōng', meaning: 'loose, pine' },
        { char: '软', pinyin: 'ruǎn', meaning: 'soft' },
        { char: '硬', pinyin: 'yìng', meaning: 'hard' },
        { char: '脆', pinyin: 'cuì', meaning: 'crisp, brittle' },
        { char: '韧', pinyin: 'rèn', meaning: 'tough, flexible' },
        { char: '弹', pinyin: 'tán', meaning: 'bounce, bullet' },
        { char: '压', pinyin: 'yā', meaning: 'press' },
        { char: '挤', pinyin: 'jǐ', meaning: 'squeeze, crowd' },
        { char: '撑', pinyin: 'chēng', meaning: 'support, prop' },
        { char: '托', pinyin: 'tuō', meaning: 'support, entrust' },
        { char: '举', pinyin: 'jǔ', meaning: 'raise, lift' },
        { char: '抬', pinyin: 'tái', meaning: 'lift, raise' },
        { char: '扛', pinyin: 'káng', meaning: 'carry on shoulder' },
        { char: '担', pinyin: 'dān', meaning: 'carry, bear' },
        { char: '负', pinyin: 'fù', meaning: 'bear, negative' },
        { char: '荷', pinyin: 'hé', meaning: 'lotus, load' },
        { char: '载', pinyin: 'zài', meaning: 'carry, load' },
        { char: '装', pinyin: 'zhuāng', meaning: 'install, pretend' },
        { char: '卸', pinyin: 'xiè', meaning: 'unload' },
        { char: '拆', pinyin: 'chāi', meaning: 'dismantle' },
        { char: '修', pinyin: 'xiū', meaning: 'repair, build' },
        { char: '建', pinyin: 'jiàn', meaning: 'build' },
        { char: '筑', pinyin: 'zhù', meaning: 'build, construct' },
        { char: '造', pinyin: 'zào', meaning: 'make, create' },
        { char: '创', pinyin: 'chuàng', meaning: 'create' },
        { char: '设', pinyin: 'shè', meaning: 'set up, design' },
        { char: '立', pinyin: 'lì', meaning: 'stand, establish' },
        { char: '置', pinyin: 'zhì', meaning: 'place, set' },
        { char: '摆', pinyin: 'bǎi', meaning: 'put, arrange' },
        { char: '陈', pinyin: 'chén', meaning: 'display, old' },
        { char: '列', pinyin: 'liè', meaning: 'list, row' },
        { char: '序', pinyin: 'xù', meaning: 'order, preface' },
        { char: '秩', pinyin: 'zhì', meaning: 'order' },
        { char: '纪', pinyin: 'jì', meaning: 'discipline, era' },
        { char: '律', pinyin: 'lǜ', meaning: 'law, rule' }
    ],
    6: [
        { char: '抽', pinyin: 'chōu', meaning: 'draw out, abstract' },
        { char: '象', pinyin: 'xiàng', meaning: 'image, abstract' },
        { char: '概', pinyin: 'gài', meaning: 'general, approximate' },
        { char: '括', pinyin: 'kuò', meaning: 'include, bracket' },
        { char: '综', pinyin: 'zōng', meaning: 'sum up' },
        { char: '合', pinyin: 'hé', meaning: 'combine, together' },
        { char: '统', pinyin: 'tǒng', meaning: 'system, unite' },
        { char: '一', pinyin: 'yī', meaning: 'one, unite' },
        { char: '整', pinyin: 'zhěng', meaning: 'whole, tidy' },
        { char: '体', pinyin: 'tǐ', meaning: 'body, system' },
        { char: '局', pinyin: 'jú', meaning: 'bureau, situation' },
        { char: '部', pinyin: 'bù', meaning: 'part, ministry' },
        { char: '分', pinyin: 'fēn', meaning: 'divide, part' },
        { char: '析', pinyin: 'xī', meaning: 'analyze' },
        { char: '解', pinyin: 'jiě', meaning: 'solve, analyze' },
        { char: '剖', pinyin: 'pōu', meaning: 'dissect' },
        { char: '割', pinyin: 'gē', meaning: 'cut' },
        { char: '裂', pinyin: 'liè', meaning: 'split, crack' },
        { char: '破', pinyin: 'pò', meaning: 'break' },
        { char: '碎', pinyin: 'suì', meaning: 'broken, fragment' },
        { char: '残', pinyin: 'cán', meaning: 'incomplete, cruel' },
        { char: '缺', pinyin: 'quē', meaning: 'lack, defect' },
        { char: '乏', pinyin: 'fá', meaning: 'lack, tired' },
        { char: '贫', pinyin: 'pín', meaning: 'poor' },
        { char: '匮', pinyin: 'kuì', meaning: 'lack, deficient' },
        { char: '竭', pinyin: 'jié', meaning: 'exhaust' },
        { char: '尽', pinyin: 'jìn', meaning: 'exhaust, end' },
        { char: '穷', pinyin: 'qióng', meaning: 'poor, exhaust' },
        { char: '极', pinyin: 'jí', meaning: 'extreme, pole' },
        { char: '端', pinyin: 'duān', meaning: 'end, proper' },
        { char: '顶', pinyin: 'dǐng', meaning: 'top, apex' },
        { char: '峰', pinyin: 'fēng', meaning: 'peak' },
        { char: '巅', pinyin: 'diān', meaning: 'summit' },
        { char: '颠', pinyin: 'diān', meaning: 'top, jolt' },
        { char: '倒', pinyin: 'dǎo', meaning: 'fall, invert' },
        { char: '翻', pinyin: 'fān', meaning: 'turn over' },
        { char: '覆', pinyin: 'fù', meaning: 'cover, overturn' },
        { char: '盖', pinyin: 'gài', meaning: 'cover, lid' },
        { char: '罩', pinyin: 'zhào', meaning: 'cover, shade' },
        { char: '遮', pinyin: 'zhē', meaning: 'block, cover' },
        { char: '蔽', pinyin: 'bì', meaning: 'cover, shelter' },
        { char: '隐', pinyin: 'yǐn', meaning: 'hide' },
        { char: '藏', pinyin: 'cáng', meaning: 'hide, store' },
        { char: '埋', pinyin: 'mái', meaning: 'bury' },
        { char: '葬', pinyin: 'zàng', meaning: 'bury' },
        { char: '殉', pinyin: 'xùn', meaning: 'die for' },
        { char: '牺', pinyin: 'xī', meaning: 'sacrifice' },
        { char: '献', pinyin: 'xiàn', meaning: 'offer, dedicate' },
        { char: '贡', pinyin: 'gòng', meaning: 'tribute, contribute' },
        { char: '奉', pinyin: 'fèng', meaning: 'offer, serve' },
        { char: '侍', pinyin: 'shì', meaning: 'serve, attend' },
        { char: '伺', pinyin: 'sì', meaning: 'watch, serve' },
        { char: '候', pinyin: 'hòu', meaning: 'wait, time' },
        { char: '待', pinyin: 'dài', meaning: 'wait, treat' },
        { char: '遇', pinyin: 'yù', meaning: 'meet, treat' },
        { char: '逢', pinyin: 'féng', meaning: 'meet' },
        { char: '碰', pinyin: 'pèng', meaning: 'bump, meet' },
        { char: '撞', pinyin: 'zhuàng', meaning: 'bump, collide' },
        { char: '击', pinyin: 'jī', meaning: 'hit, attack' },
        { char: '打', pinyin: 'dǎ', meaning: 'hit, strike' },
        { char: '敲', pinyin: 'qiāo', meaning: 'knock' },
        { char: '捶', pinyin: 'chuí', meaning: 'beat, pound' },
        { char: '砸', pinyin: 'zá', meaning: 'smash' },
        { char: '劈', pinyin: 'pī', meaning: 'split, chop' },
        { char: '斩', pinyin: 'zhǎn', meaning: 'chop, behead' },
        { char: '砍', pinyin: 'kǎn', meaning: 'chop, cut' },
        { char: '削', pinyin: 'xuē', meaning: 'peel, cut' },
        { char: '刮', pinyin: 'guā', meaning: 'scrape, blow' },
        { char: '擦', pinyin: 'cā', meaning: 'wipe, rub' },
        { char: '抹', pinyin: 'mǒ', meaning: 'wipe, smear' },
        { char: '涂', pinyin: 'tú', meaning: 'smear, spread' },
        { char: '染', pinyin: 'rǎn', meaning: 'dye, infect' },
        { char: '浸', pinyin: 'jìn', meaning: 'soak, immerse' },
        { char: '泡', pinyin: 'pào', meaning: 'soak, bubble' },
        { char: '沾', pinyin: 'zhān', meaning: 'moisten, touch' },
        { char: '湿', pinyin: 'shī', meaning: 'wet' },
        { char: '润', pinyin: 'rùn', meaning: 'moist, smooth' },
        { char: '滑', pinyin: 'huá', meaning: 'slippery, slide' },
        { char: '溜', pinyin: 'liū', meaning: 'slip, slide' },
        { char: '滚', pinyin: 'gǔn', meaning: 'roll' },
        { char: '转', pinyin: 'zhuǎn', meaning: 'turn, rotate' },
        { char: '旋', pinyin: 'xuán', meaning: 'revolve, spin' },
        { char: '绕', pinyin: 'rào', meaning: 'wind, circle' },
        { char: '缠', pinyin: 'chán', meaning: 'wind, wrap' },
        { char: '卷', pinyin: 'juǎn', meaning: 'roll, volume' },
        { char: '折', pinyin: 'zhé', meaning: 'fold, break' },
        { char: '弯', pinyin: 'wān', meaning: 'bend, curved' },
        { char: '曲', pinyin: 'qū', meaning: 'curved, song' },
        { char: '扭', pinyin: 'niǔ', meaning: 'twist' },
        { char: '拧', pinyin: 'nǐng', meaning: 'twist, wring' },
        { char: '搓', pinyin: 'cuō', meaning: 'rub, twist' },
        { char: '揉', pinyin: 'róu', meaning: 'knead, rub' },
        { char: '捏', pinyin: 'niē', meaning: 'pinch, knead' },
        { char: '握', pinyin: 'wò', meaning: 'hold, grasp' },
        { char: '抓', pinyin: 'zhuā', meaning: 'grab, scratch' },
        { char: '攥', pinyin: 'zuàn', meaning: 'grip, clench' },
        { char: '捧', pinyin: 'pěng', meaning: 'hold in hands' },
        { char: '掬', pinyin: 'jū', meaning: 'hold in hands' },
        { char: '捞', pinyin: 'lāo', meaning: 'scoop up' },
        { char: '掏', pinyin: 'tāo', meaning: 'pull out, dig' }
    ]
};
